version: "3.3"

services:
  flasktmp:
    container_name: flasktmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flasktmp.rule=PathPrefix(`/t`)"
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: production